package invgo

// ImplementedEndpoints when adding a new Invgate endpoint
// this must be updated so that the coverage script knows which
// endpoints Invgo supports calling.
var ImplementedEndpoints = map[string][]string{
	"/breakingnews":                     {"POST", "PUT", "GET"},
	"/breakingnews.all":                 {"GET"},
	"/breakingnews.attributes.status":   {"GET"},
	"/breakingnews.attributes.type":     {"GET"},
	"/breakingnews.status":              {"POST", "GET"},
	"/categories":                       {"GET"},
	"/helpdesks":                        {"GET"},
	"/incident":                         {"POST", "PUT", "GET"},
	"/incident.attributes.status":       {"GET"},
	"/incident.attributes.type":         {"GET"},
	"/incidents":                        {"GET"},
	"/incidents.approval":               {"GET"},
	"/incidents.approval.accept":        {"PUT"},
	"/incidents.approval.cancel":        {"PUT"},
	"/incidents.approval.reject":        {"PUT"},
	"/incidents.approval.status":        {"GET"},
	"/incidents.approval.type":          {"GET"},
	"/incidents.approval.vote_status":   {"GET"},
	"/incidents.by.status":              {"GET"},
	"/sd.version":                       {"GET"},
	"/timetracking":                     {"GET", "POST", "DELETE"},
	"/timetracking.attributes.category": {"GET"},
	"/triggers":                         {"GET"},
	"/triggers.executions":              {"GET"},
	"/user":                             {"GET", "POST", "PUT", "DELETE"},
	"/user.by":                          {"GET"},
	"/user.convert":                     {"POST"},
	"/user.disable":                     {"PUT"},
	"/user.enable":                      {"PUT"},
	"/user.password":                    {"PUT"},
	"/user.password.reset":              {"POST"},
	"/user.token":                       {"POST"},
	"/users":                            {"GET"},
	"/users.by":                         {"GET"},
	"/users.groups":                     {"GET"},
	"/wf.deploy":                        {"PUT"},
	"/wf.initialfields.by.category":     {"GET"},
}
