package invgo

// ImplementedEndpoints when adding a new Invgate endpoint
// this must be updated so that the coverage script knows which
// endpoints Invgo supports calling.
var ImplementedEndpoints = map[string][]string{
	"/breakingnews":                      {"POST", "PUT", "GET"},
	"/breakingnews.all":                  {"GET"},
	"/breakingnews.attributes.status":    {"GET"},
	"/breakingnews.attributes.type":      {"GET"},
	"/breakingnews.status":               {"POST", "GET"},
	"/categories":                        {"GET"},
	"/helpdesks":                         {"GET"},
	"/incident":                          {"POST", "PUT", "GET"},
	"/incident.approval":                 {"GET"},
	"/incident.approval.accept":          {"PUT"},
	"/incident.approval.add_voter":       {"POST"},
	"/incident.approval.cancel":          {"PUT"},
	"/incident.approval.possible_voters": {"GET"},
	"/incident.approval.reject":          {"PUT"},
	"/incident.approval.status":          {"GET"},
	"/incident.approval.type":            {"GET"},
	"/incident.approval.vote_status":     {"GET"},
	"/incident.attachment":               {"GET"},
	"/incident.attributes.priority":      {"GET"},
	"/incident.attributes.source":        {"GET"},
	"/incident.attributes.status":        {"GET"},
	"/incident.attributes.type":          {"GET"},
	"/incident.cancel":                   {"POST"},
	"/incident.comment":                  {"POST", "GET"},
	"/incidents":                         {"GET"},
	"/incidents.by.status":               {"GET"},
	"/sd.version":                        {"GET"},
	"/timetracking":                      {"GET", "POST", "DELETE"},
	"/timetracking.attributes.category":  {"GET"},
	"/triggers":                          {"GET"},
	"/triggers.executions":               {"GET"},
	"/user":                              {"GET", "POST", "PUT", "DELETE"},
	"/user.by":                           {"GET"},
	"/user.convert":                      {"POST"},
	"/user.disable":                      {"PUT"},
	"/user.enable":                       {"PUT"},
	"/user.password":                     {"PUT"},
	"/user.password.reset":               {"POST"},
	"/user.token":                        {"POST"},
	"/users":                             {"GET"},
	"/users.by":                          {"GET"},
	"/users.groups":                      {"GET"},
	"/wf.deploy":                         {"PUT"},
	"/wf.initialfields.by.category":      {"GET"},
}
